# Generated by Django 5.2.7 on 2025-12-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpromoter',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_promoters', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventpromoter',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_events', to='users.promoterprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventstatuses'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventvenues'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='participants.deviceprofile'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_rsvps', to='users.promoterprofile'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.rsvpsources'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.rsvpstatuses'),
        ),
        migrations.AddIndex(
            model_name='eventpromoter',
            index=models.Index(fields=['event', 'is_active'], name='event_promo_event_i_3596e4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpromoter',
            index=models.Index(fields=['promoter', 'is_active'], name='event_promo_promote_61ef85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventpromoter',
            unique_together={('event', 'promoter')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organiser', 'status'], name='events_organis_4398b2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['event', 'status'], name='rsvps_event_i_3b5891_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['device'], name='rsvps_device__e474d8_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['promoter', 'event'], name='rsvps_promote_1f5ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['created_at'], name='rsvps_created_12ed6f_idx'),
        ),
    ]
